language: scala
scala:
- 2.11.8
jdk: oraclejdk8
branches:
  only:
  - master
cache:
  directories:
  - $HOME/.sbt/0.13
  - $HOME/.sbt/boot/scala*
  - $HOME/.sbt/cache
  - $HOME/.sbt/launchers
  - $HOME/.ivy2
before_cache:
- du -h -d 1 $HOME/.ivy2/
- du -h -d 2 $HOME/.sbt/
- find $HOME/.sbt -name "*.lock" -type f -delete
- find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete
env:
  matrix:
  - TRAVIS_NESTED_LAMBDA=facia-purger
  global:
  - secure: O/2qdhemDAKuScBI6+AHLNSh9C2yZIIq27VifgUj+x+89IQUI+Sy7Tz2hzvlrM9vXwLkqQgfReS8bZuOg1nHeQOt8jA/Mb06xvqe86nHpviy4DR3f1Pfqkm3lkAiv2eRyvivjfRicV96Fij3JmbTvtvk4LumnogYaYILwGCXfiiFiCpJMmgsOIZAQYMvTBfck2zvxvRZGReewWGSBsLkyrxycETXFNcNQwF/RWBb9noZkOf8O8g2vySB/aREhVd5xGtxDAgZEnoW/alcBJh4kp0J3L2SXVUMmPhLfH4cDkBjZv1biHeJCE2js89FD+mCPak83v5FL5JE87MR2peLu1bheMlRcukyewCr1CN5gjScyRA4zgsiZkSz1fYiPI9Z2MMLUNUTh/yAM7Kmw0PHd3v1LzBxGVV87WAHJhsUkGT+CKoJcpkhHlx1ErCeV8Ly2L5xtmwpc4zuGytOBWyPuDwKajYc2z/kO7+1aJTxNELinEWcJWJySKGTLB6oj50EmO7VWgv1GL43OL8BvsFhwDvu5Jml4KiHoxdmzhswLkTbirkFm3bn77HbNgfNNxRfmig9sDrYekMKrLOrf9AdPCdZB/oDOhArvgp9ExxKHvOux91n21Q0rkurl9GYJr7qIm1Ll7+jccIjh6ID/j1uSGWpdCBPlgFX7jVNzATumfs=
  - secure: aVGHnA/1Or5hclfppfj/3/NFYeE6RqGvO6XxQquCYbtWSOC4m/WMqbRd5X+RrNvbCPu5jtATe+4CiGWMwkuVbsKtnGN4wNBoORs8NlabqlFevTZJNdIbcH11RNJuFzgAwh3HYZklndUjYFVPAEEgJUWz/Y4chz+FEbBVimsA2V5JZFEXkuKNTuA1TpFdxF7K9gQrZEMuTO5U5N9JjjVUOFdfQOG90aU9eEWpFImHBs5ueieyTAnH48fsXrB8ZkPnPg6mbd/noSHPwAIXoQ+LgS/Fzj415i5MyGY3Uys6G4/ohSscWXqqIP45i/sUAs8yrsC+WsRXaANjcolt4kO4ySfyg4dotIOZkhnuPvJMmf0XSWje0smYD0wRkcGCkwGlRMmf3HmDuFHE+8mOBFxNo7YyeoegEt97tfUzq7VWm9djhIj/n52pRWg8PdGRHVtrfSGXSBF5bo9nf0k25Oxg4WGLpFDwrp6GCCEJUDt3K/HwLa1SmcYCRkDUlD351nccOrah/DxUbM/0lwWRe7BtXYCQ8Z+WpZwhHlPFc0GqX4unf2d/TF+BuZL4gW+5aYEZUz9Z2UvVUHXdUQtpCe/NP2uYv6cbH231OylhQpWaK+Q/E9NIcnaJcHWydSyTw1mM5GNL99XVAA7MTgzMDbYPiwPa/8HWvBsdxkFEwDMT+PA=
script: cd $TRAVIS_NESTED_LAMBDA && sbt riffRaffBuildIdentifier clean test riffRaffUpload
